name: Build & Test

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
